### ISSUE TITLE
problem with lib.es6.d.ts ?

### ISSUE THREAD

**Issue by csrow** [Souldrinker/vs-skeleton#1]
After coping over the lib.es6.d.ts file, when I try to build the project I am getting multiple
"Computed property names are not allowed in interfaces." errors all in the lib.es6.d.ts file.  
Am I missing something? How are you able to build the project?

**Comment by Souldrinker** [comment]
Sorry, the link I had to the lib.es6.d.ts in the readme incorrectly pointed at the master branch which is now changed for the upcoming 1.5 release. I've now updated the readme file to point to the correct version of the file, which is here: https://github.com/Microsoft/TypeScript/blob/release-1.4/bin/lib.es6.d.ts.
